### ISSUE TITLE
main 또는 develop에 직접적인 push

### ISSUE THREAD

**Issue by peterjr123** [Y-s-children/projectYS#5]
실수로, 혹은 잘 모르고 main 또는 develop에 직접적인 push가 일어나는 것을 방지하기 위해서,
main과 develop에 push를 금지하고, PR로만 가능하도록 branch를 설정했어요.

PR같은 경우도 자신을 제외한 2명의 허락이 있어야 가능하도록 변경했으니 참고하세요~~

(이전에 일어났던 우리 모두의 실수들은... 관대한 마음으로 서로서로 눈감아 줍시다... 다들 처음이잖아요...? 아닝가...?)

참고 문헌 : [https://kotlinworld.com/292](https://kotlinworld.com/292)

모두 확인하고 나면 close 해주세요~~ (혹시 다른 의견있으면 회의 때 다시한번 언급할 테니 그때 의견 주세요~)
- [x] DDD
- [x] 나이트메어
- [x] 커비

**Comment by chb09876** [comment]
https://goodgid.github.io/Github-CODEOWNERS/
해당 기능을 사용하면 PR시 리뷰어를 자동으로 할당할 수 있습니다.
보시고 괜찮으면 적용해도 될것같습니다! 👍
